apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-finchley
  namespace: finchley
spec:
  storageClassName: database
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi